# Generated by Django 4.0.2 on 2022-03-30 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteItemCount', models.PositiveIntegerField(default=0)),
                ('siteItemStatus', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Low'), (3, 'Empty')], default=1)),
                ('siteItemTurnover', models.CharField(choices=[('S', 'Slow'), ('N', 'Normal'), ('F', 'Fast')], default='F', max_length=1)),
                ('siteItemMinThreshold', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site', models.AutoField(primary_key=True, serialize=False)),
                ('siteName', models.CharField(blank=True, max_length=50)),
                ('siteStreetNumber', models.CharField(blank=True, max_length=30)),
                ('siteStreet', models.CharField(blank=True, max_length=30)),
                ('siteBarangay', models.CharField(max_length=30)),
                ('siteCity', models.CharField(max_length=35)),
                ('siteProvince', models.CharField(max_length=30)),
                ('siteRegion', models.CharField(max_length=30)),
                ('siteZip', models.CharField(blank=True, max_length=10)),
                ('siteContactNo', models.CharField(max_length=11)),
                ('inventory_items', models.ManyToManyField(blank=True, related_name='inventory_items', through='project_site.Inventory', to='item.Item')),
                ('siteCart', models.ManyToManyField(blank=True, related_name='siteCart', through='project_site.Cart', to='item.Item')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_site.site'),
        ),
        migrations.AddField(
            model_name='cart',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_site.site'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('item', 'site'), name='unique_item_inv'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('cartItem', 'site')},
        ),
    ]
