# Generated by Django 4.0.2 on 2022-03-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('itemID', 'siteID'), name='unique_item_inv'),
        ),
    ]
