# Generated by Django 4.0.2 on 2022-03-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='siteName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
