# Generated by Django 4.0.2 on 2022-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0002_cart_cartitemcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='siteItemStatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Excessive Count'), (1, 'Within Threshold'), (2, 'Low'), (3, 'Very Low'), (4, 'Critical'), (5, 'Empty')], default=1),
        ),
    ]
