# Generated by Django 4.0.2 on 2022-05-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0003_alter_site_sitename'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventoryDateModified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
