# Generated by Django 4.0.2 on 2022-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0004_alter_inventory_siteitemstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='siteItemStatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Above Threshold'), (1, 'Moderate'), (2, 'Low'), (3, 'Critical'), (4, 'Empty')], default=1),
        ),
    ]
