# Generated by Django 4.0.2 on 2022-03-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userContactNo',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userMiddleName',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userRole',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userSuffix',
            new_name='suffix',
        ),
    ]
