# Generated by Django 4.0.2 on 2022-03-30 09:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_usercontactno_user_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[users.models.validate_capitalized]),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, validators=[users.models.validate_capitalized]),
        ),
    ]
