# Generated by Django 4.0.2 on 2022-03-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_site', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_Requisition',
            fields=[
                ('reqID', models.AutoField(primary_key=True, serialize=False)),
                ('reqDescription', models.CharField(max_length=1000)),
                ('reqDateSubmitted', models.DateTimeField(auto_now=True)),
                ('reqDateNeeded', models.DateTimeField()),
                ('reqStatus', models.PositiveSmallIntegerField(choices=[(0, 'For Review'), (1, 'Awaiting Delivery'), (2, 'Request Denied'), (3, 'Delivered')], default=0)),
                ('originSiteID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='originSite', to='project_site.site')),
                ('reqItems', models.ManyToManyField(to='item.Item')),
                ('siteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationSite', to='project_site.site')),
            ],
        ),
    ]
