# Generated by Django 4.0.2 on 2022-04-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequisition',
            name='originSite',
        ),
    ]
