# Generated by Django 4.0.2 on 2022-03-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0002_initial'),
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequisition',
            name='originSite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originSite', to='project_site.site'),
        ),
    ]
