# Generated by Django 4.0.2 on 2022-03-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequisition',
            name='reqDescription',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
