# Generated by Django 4.0.2 on 2022-03-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_requisition_items',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material_requisition',
            name='reqDescription',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
