# Generated by Django 4.0.2 on 2022-03-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0002_material_requisition_items_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_requisition',
            name='reqDateNeeded',
            field=models.DateField(),
        ),
    ]
