# Generated by Django 4.0.2 on 2022-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_alter_materialrequisition_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequisition',
            name='reqStatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'For Review'), (1, 'Partially Filled'), (2, 'Request Denied'), (3, 'Filled'), (4, 'Delivered')], default=0),
        ),
    ]
