# Generated by Django 4.0.2 on 2022-03-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0004_remove_material_requisition_items_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_requisition',
            name='reqItemsID',
        ),
    ]
