# Generated by Django 4.0.2 on 2022-04-06 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0001_initial'),
        ('requisition', '0003_alter_materialrequisition_site'),
        ('item', '0001_initial'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTransfer',
            fields=[
                ('transfer', models.AutoField(primary_key=True, serialize=False)),
                ('transferDateSubmitted', models.DateField()),
                ('transferStatus', models.PositiveSmallIntegerField(choices=[(0, 'For Review'), (1, 'Awaiting Delivery'), (2, 'Transfer Pending'), (3, 'Transfer Accomplished')], default=0)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisition.materialrequisition')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_site.site')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransferItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemQuantity', models.PositiveIntegerField(default=0, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.materialtransfer')),
            ],
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.AddField(
            model_name='materialtransfer',
            name='transferItems',
            field=models.ManyToManyField(related_name='mat_tran_items', through='transfer.MaterialTransferItems', to='item.Item'),
        ),
    ]
