# Generated by Django 4.0.2 on 2022-05-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransfer',
            name='transferDateModified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
