# Generated by Django 4.0.2 on 2022-05-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_materialtransfer_transferdatemodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransfer',
            name='transferStatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Delivery'), (1, 'Approved'), (2, 'Delivered')], default=0),
        ),
    ]
