# Generated by Django 4.0.2 on 2022-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_materialtransfer_materialtransferitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransfer',
            name='transferDateSubmitted',
            field=models.DateField(auto_now=True),
        ),
    ]
