# Generated by Django 4.0.2 on 2022-05-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_alter_materialtransfer_transferstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransfer',
            name='transferStatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved'), (2, 'Delivered')], default=0),
        ),
    ]
