# Generated by Django 4.0.2 on 2022-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_alter_materialtransfer_transferdatesubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransfer',
            name='transferStatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Delivery'), (1, 'Delivered')], default=0),
        ),
    ]
