# Generated by Django 4.0.2 on 2022-02-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
    ]
