# Generated by Django 4.0.2 on 2022-03-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0001_initial'),
        ('item', '0001_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='site_item_inventory',
            unique_together={('itemID', 'siteID')},
        ),
    ]
