# Generated by Django 4.0.2 on 2022-03-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0001_initial'),
        ('item', '0001_initial'),
        ('inventory', '0003_alter_site_item_inventory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Ordered', models.BooleanField(default=False)),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteItemCount', models.PositiveIntegerField(default=0)),
                ('siteItemStatus', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Low'), (3, 'Empty')], default=1)),
                ('siteItemTurnover', models.CharField(choices=[('S', 'Slow'), ('N', 'Normal'), ('F', 'Fast')], default='F', max_length=1)),
                ('siteItemMinThreshold', models.PositiveSmallIntegerField(default=0)),
                ('itemID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
                ('siteID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_site.site')),
            ],
            options={
                'unique_together': {('itemID', 'siteID')},
            },
        ),
        migrations.CreateModel(
            name='InventoryCart',
            fields=[
                ('siteID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project_site.site')),
                ('inventorylistID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Site_Item_Inventory',
        ),
    ]
